version: '3.1'

services:

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: "postgres:14.9"
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=movie-ticket
    volumes:
      - ~pgdata:/var/lib/postgresql/data